### ISSUE TITLE
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

### ISSUE THREAD

**Issue by DarkCeptor44** [pedroburon/dotenv#18]
This is the log:
```
(venv) H:\Programacao\Python\coolbot>pip install dotenv
Collecting dotenv
  Using cached dotenv-0.0.5.tar.gz (2.4 kB)
    ERROR: Command errored out with exit status 1:
     command: 'h:\programacao\python\coolbot\venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\MSI GX63VR\\AppData\\Local\\Temp\\pip-install-xk9gkaoe\\dotenv\\setup.py'"'"'; __file__='"'"'C:\\Users\\MSI GX63VR\\AppData\\Local\\Temp\\pip-install-xk9gkaoe\\dotenv\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\MSI GX63VR\AppData\Local\Temp\pip-pip-egg-info-sg55hrk8'
         cwd: C:\Users\MSI GX63VR\AppData\Local\Temp\pip-install-xk9gkaoe\dotenv\
    Complete output (68 lines):
    Traceback (most recent call last):
      File "h:\programacao\python\coolbot\venv\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "h:\programacao\python\coolbot\venv\lib\site-packages\setuptools\sandbox.py", line 194, in setup_context
        __import__('setuptools')
      File "C:\Users\MSIGX6~1\AppData\Local\Temp\easy_install-xy422xbf\distribute-0.7.3\setuptools\__init__.py", line 2, in <module>
      File "C:\Users\MSIGX6~1\AppData\Local\Temp\easy_install-xy422xbf\distribute-0.7.3\setuptools\extension.py", line 5, in <module>
      File "C:\Users\MSIGX6~1\AppData\Local\Temp\easy_install-xy422xbf\distribute-0.7.3\setuptools\dist.py", line 7, in <module>
      File "C:\Users\MSIGX6~1\AppData\Local\Temp\easy_install-xy422xbf\distribute-0.7.3\setuptools\command\__init__.py", line 8, in <module>
      File "C:\Users\MSIGX6~1\AppData\Local\Temp\easy_install-xy422xbf\distribute-0.7.3\setuptools\command\install_scripts.py", line 3, in <module>
      File "C:\Users\MSIGX6~1\AppData\Local\Temp\easy_install-xy422xbf\distribute-0.7.3\pkg_resources.py", line 1518, in <module>
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\MSI GX63VR\AppData\Local\Temp\pip-install-xk9gkaoe\dotenv\setup.py", line 13, in <module>
        setup(name='dotenv',
      File "h:\programacao\python\coolbot\venv\lib\site-packages\setuptools\__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "h:\programacao\python\coolbot\venv\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "h:\programacao\python\coolbot\venv\lib\site-packages\setuptools\dist.py", line 716, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "h:\programacao\python\coolbot\venv\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "h:\programacao\python\coolbot\venv\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "h:\programacao\python\coolbot\venv\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
        return installer(requirement)
      File "h:\programacao\python\coolbot\venv\lib\site-packages\setuptools\dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "h:\programacao\python\coolbot\venv\lib\site-packages\setuptools\command\easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "h:\programacao\python\coolbot\venv\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "h:\programacao\python\coolbot\venv\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "h:\programacao\python\coolbot\venv\lib\site-packages\setuptools\command\easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "h:\programacao\python\coolbot\venv\lib\site-packages\setuptools\command\easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "h:\programacao\python\coolbot\venv\lib\site-packages\setuptools\sandbox.py", line 233, in run_setup
        with setup_context(setup_dir):
      File "C:\Program Files\Python38\lib\contextlib.py", line 113, in __enter__
        return next(self.gen)
      File "h:\programacao\python\coolbot\venv\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "C:\Program Files\Python38\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "h:\programacao\python\coolbot\venv\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "h:\programacao\python\coolbot\venv\lib\site-packages\setuptools\sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "h:\programacao\python\coolbot\venv\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "h:\programacao\python\coolbot\venv\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "h:\programacao\python\coolbot\venv\lib\site-packages\setuptools\sandbox.py", line 194, in setup_context
        __import__('setuptools')
      File "C:\Users\MSIGX6~1\AppData\Local\Temp\easy_install-xy422xbf\distribute-0.7.3\setuptools\__init__.py", line 2, in <module>
      File "C:\Users\MSIGX6~1\AppData\Local\Temp\easy_install-xy422xbf\distribute-0.7.3\setuptools\extension.py", line 5, in <module>
      File "C:\Users\MSIGX6~1\AppData\Local\Temp\easy_install-xy422xbf\distribute-0.7.3\setuptools\dist.py", line 7, in <module>
      File "C:\Users\MSIGX6~1\AppData\Local\Temp\easy_install-xy422xbf\distribute-0.7.3\setuptools\command\__init__.py", line 8, in <module>
      File "C:\Users\MSIGX6~1\AppData\Local\Temp\easy_install-xy422xbf\distribute-0.7.3\setuptools\command\install_scripts.py", line 3, in <module>
      File "C:\Users\MSIGX6~1\AppData\Local\Temp\easy_install-xy422xbf\distribute-0.7.3\pkg_resources.py", line 1518, in <module>
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
```

**Comment by antimora** [comment]
I had the same issue. @DarkCeptor44 the fix is to install python-dotenv per: https://github.com/theskumar/python-dotenv/issues/113

**Comment by DarkCeptor44** [comment]
That works thank you.
