### ISSUE TITLE
Error in Python 3

### ISSUE THREAD

**Issue by alejandrogmvva2** [pedroburon/dotenv#19]
ERROR: Command errored out with exit status 1:
     command: /opt/virtualenvs/python3/bin/python3 -c 'import sys, setupto
ols, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-93oq0tm_/dotenv/setup.p
y'"'"'; __file__='"'"'/tmp/pip-install-93oq0tm_/dotenv/setup.py'"'"';f=get
attr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'
\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'
"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-6coih9jp
         cwd: /tmp/pip-install-93oq0tm_/dotenv/
    Complete output (51 lines):
        ERROR: Command errored out with exit status 1:
         command: /opt/virtualenvs/python3/bin/python3 -c 'import sys, set
uptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-igbsd_sp/distribute/s
etup.py'"'"'; __file__='"'"'/tmp/pip-wheel-igbsd_sp/distribute/setup.py'"'
"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().repla
ce('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"
'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-0u99wf9x
             cwd: /tmp/pip-wheel-igbsd_sp/distribute/
        Complete output (15 lines):
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-wheel-igbsd_sp/distribute/setuptools/__init__.py"
, line 2, in <module>
            from setuptools.extension import Extension, Library
          File "/tmp/pip-wheel-igbsd_sp/distribute/setuptools/extension.py", line 5, in <module>
            from setuptools.dist import _get_unpatched
          File "/tmp/pip-wheel-igbsd_sp/distribute/setuptools/dist.py", line 7, in <module>
            from setuptools.command.install import install
          File "/tmp/pip-wheel-igbsd_sp/distribute/setuptools/command/__init__.py", line 8, in <module>
            from setuptools.command import install_scripts
          File "/tmp/pip-wheel-igbsd_sp/distribute/setuptools/command/install_scripts.py", line 3, in <module>
            from pkg_resources import Distribution, PathMetadata, ensure_directory
          File "/tmp/pip-wheel-igbsd_sp/distribute/pkg_resources.py", line 1518, in <module>
            register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
        AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
        ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    Traceback (most recent call last):
      File "/opt/virtualenvs/python3/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/opt/virtualenvs/python3/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpf9yy1f6o', '--quiet', 'distribute']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-93oq0tm_/dotenv/setup.py", line 13, in <module>
        setup(name='dotenv',
      File "/opt/virtualenvs/python3/lib/python3.8/site-packages/setuptools/__init__.py", line 160, in setup
        _install_setup_requires(attrs)
      File "/opt/virtualenvs/python3/lib/python3.8/site-packages/setuptools/__init__.py", line 155, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/opt/virtualenvs/python3/lib/python3.8/site-packages/setuptools/dist.py", line 695, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/opt/virtualenvs/python3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "/opt/virtualenvs/python3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/opt/virtualenvs/python3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/opt/virtualenvs/python3/lib/python3.8/site-packages/setuptools/dist.py", line 754, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/opt/virtualenvs/python3/lib/python3.8/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/opt/virtualenvs/python3/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpf9yy1f6o', '--quiet', 'distribute']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by DrDabbidy** [comment]
I also have the exact same issue.

**Comment by EmilStenstrom** [comment]
There are hundreds of people having the same issue. The answer is to install the "python-dotenv" package instead of the "dotenv" package.

**Comment by Sayyed-Salman** [comment]
this project is probably dead 💀, ```pip install python-dotenv``` is the answer to every question.
