### ISSUE TITLE
Issue installing with `pipenv `

### ISSUE THREAD

**Issue by Sayyed-Salman** [pedroburon/dotenv#23]
# Error while installing with pipenv 

This pops out while trying to install with pipenv on python 3.10.0
```
Loading .env environment variables...
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Installing dotenv...
[  ==] Installing dotenv...[31m[1mError: [0m An error occurred while installing [32mdotenv[0m!
Error text: Collecting dotenv
  Downloading dotenv-0.0.5.tar.gz (2.4 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

[    ] Installing dotenv...[36m  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [71 lines of output]
      C:\Users\Acer\.virtualenvs\tate-bois-96ZGWPKM\lib\site-packages\setuptools\installer.py:27:
SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.    
        warnings.warn(
        error: subprocess-exited-with-error

        Ã— python setup.py egg_info did not run successfully.
        â”‚ exit code: 1
        â•°â”€> [21 lines of output]
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 14, in <module>
              File
"C:\Users\Acer\AppData\Local\Temp\pip-wheel-igaoeoe8\distribute_91bd652c93664ef384252db0352b544d\setuptools\__init__.py", line
2, in <module>
                from setuptools.extension import Extension, Library
              File
"C:\Users\Acer\AppData\Local\Temp\pip-wheel-igaoeoe8\distribute_91bd652c93664ef384252db0352b544d\setuptools\extension.py",    
line 5, in <module>
                from setuptools.dist import _get_unpatched
              File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
              File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
              File "C:\Users\Acer\.virtualenvs\tate-bois-96ZGWPKM\lib\site-packages\_virtualenv.py", line 89, in exec_module  
                old(module)
              File
"C:\Users\Acer\AppData\Local\Temp\pip-wheel-igaoeoe8\distribute_91bd652c93664ef384252db0352b544d\setuptools\dist.py", line 7, 
in <module>
                from setuptools.command.install import install
              File
"C:\Users\Acer\AppData\Local\Temp\pip-wheel-igaoeoe8\distribute_91bd652c93664ef384252db0352b544d\setuptools\command\__init__.p
y", line 8, in <module>
                from setuptools.command import install_scripts
              File
"C:\Users\Acer\AppData\Local\Temp\pip-wheel-igaoeoe8\distribute_91bd652c93664ef384252db0352b544d\setuptools\command\install_sc
ripts.py", line 3, in <module>
                from pkg_resources import Distribution, PathMetadata, ensure_directory
              File
"C:\Users\Acer\AppData\Local\Temp\pip-wheel-igaoeoe8\distribute_91bd652c93664ef384252db0352b544d\pkg_resources.py", line 1518,
in <module>
                register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
            AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'


        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed

      Ã— Encountered error while generating package metadata.
      â•°â”€> See above for output.

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      Traceback (most recent call last):
        File "C:\Users\Acer\.virtualenvs\tate-bois-96ZGWPKM\lib\site-packages\setuptools\installer.py", line 82, in
fetch_build_egg
          subprocess.check_call(cmd)
        File "C:\Users\Acer\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Users\\Acer\\.virtualenvs\\tate-bois-96ZGWPKM\\Scripts\\python.exe', '-m',
'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\Acer\\AppData\\Local\\Temp\\tmp9okbbypj',       
'--quiet', 'distribute']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Acer\AppData\Local\Temp\pip-install-0d2di4_i\dotenv_2c6d416c54b94d5991ff437931b4f34c\setup.py", line   
13, in <module>
          setup(name='dotenv',
        File "C:\Users\Acer\.virtualenvs\tate-bois-96ZGWPKM\lib\site-packages\setuptools\__init__.py", line 86, in setup      
          _install_setup_requires(attrs)
        File "C:\Users\Acer\.virtualenvs\tate-bois-96ZGWPKM\lib\site-packages\setuptools\__init__.py", line 80, in
_install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "C:\Users\Acer\.virtualenvs\tate-bois-96ZGWPKM\lib\site-packages\setuptools\dist.py", line 874, in
fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "C:\Users\Acer\.virtualenvs\tate-bois-96ZGWPKM\lib\site-packages\pkg_resources\__init__.py", line 815, in resolve
          dist = self._resolve_dist(
        File "C:\Users\Acer\.virtualenvs\tate-bois-96ZGWPKM\lib\site-packages\pkg_resources\__init__.py", line 851, in        
_resolve_dist
          dist = best = env.best_match(
        File "C:\Users\Acer\.virtualenvs\tate-bois-96ZGWPKM\lib\site-packages\pkg_resources\__init__.py", line 1123, in       

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
[0m
This is likely caused by a bug in [32mdotenv[0m. Report this to its maintainers.
Installation Failed
```

# Pipfile 
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
flask = "*"
flask-login = "*"
requests = "*"

[dev-packages]
autopep8 = "*"

[requires]
python_version = "3.10"
```

**Comment by andrebadini** [comment]
> # Error while installing with pipenv
> This pops out while trying to install with pipenv on python 3.10.0
> 
> ```
> Loading .env environment variables...
> Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
> Installing dotenv...
> [  ==] Installing dotenv...[31m[1mError: [0m An error occurred while installing [32mdotenv[0m!
> Error text: Collecting dotenv
>   Downloading dotenv-0.0.5.tar.gz (2.4 kB)
>   Preparing metadata (setup.py): started
>   Preparing metadata (setup.py): finished with status 'error'
> 
> [    ] Installing dotenv...[36m  error: subprocess-exited-with-error
> 
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [71 lines of output]
>       C:\Users\Acer\.virtualenvs\tate-bois-96ZGWPKM\lib\site-packages\setuptools\installer.py:27:
> SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.    
>         warnings.warn(
>         error: subprocess-exited-with-error
> 
>         Ã— python setup.py egg_info did not run successfully.
>         â”‚ exit code: 1
>         â•°â”€> [21 lines of output]
>             Traceback (most recent call last):
>               File "<string>", line 2, in <module>
>               File "<pip-setuptools-caller>", line 14, in <module>
>               File
> "C:\Users\Acer\AppData\Local\Temp\pip-wheel-igaoeoe8\distribute_91bd652c93664ef384252db0352b544d\setuptools\__init__.py", line
> 2, in <module>
>                 from setuptools.extension import Extension, Library
>               File
> "C:\Users\Acer\AppData\Local\Temp\pip-wheel-igaoeoe8\distribute_91bd652c93664ef384252db0352b544d\setuptools\extension.py",    
> line 5, in <module>
>                 from setuptools.dist import _get_unpatched
>               File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>               File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>               File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>               File "C:\Users\Acer\.virtualenvs\tate-bois-96ZGWPKM\lib\site-packages\_virtualenv.py", line 89, in exec_module  
>                 old(module)
>               File
> "C:\Users\Acer\AppData\Local\Temp\pip-wheel-igaoeoe8\distribute_91bd652c93664ef384252db0352b544d\setuptools\dist.py", line 7, 
> in <module>
>                 from setuptools.command.install import install
>               File
> "C:\Users\Acer\AppData\Local\Temp\pip-wheel-igaoeoe8\distribute_91bd652c93664ef384252db0352b544d\setuptools\command\__init__.p
> y", line 8, in <module>
>                 from setuptools.command import install_scripts
>               File
> "C:\Users\Acer\AppData\Local\Temp\pip-wheel-igaoeoe8\distribute_91bd652c93664ef384252db0352b544d\setuptools\command\install_sc
> ripts.py", line 3, in <module>
>                 from pkg_resources import Distribution, PathMetadata, ensure_directory
>               File
> "C:\Users\Acer\AppData\Local\Temp\pip-wheel-igaoeoe8\distribute_91bd652c93664ef384252db0352b544d\pkg_resources.py", line 1518,
> in <module>
>                 register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
>             AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
> 
> 
>         note: This error originates from a subprocess, and is likely not a problem with pip.
>       error: metadata-generation-failed
> 
>       Ã— Encountered error while generating package metadata.
>       â•°â”€> See above for output.
> 
>       note: This is an issue with the package mentioned above, not pip.
>       hint: See above for details.
>       Traceback (most recent call last):
>         File "C:\Users\Acer\.virtualenvs\tate-bois-96ZGWPKM\lib\site-packages\setuptools\installer.py", line 82, in
> fetch_build_egg
>           subprocess.check_call(cmd)
>         File "C:\Users\Acer\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
>           raise CalledProcessError(retcode, cmd)
>       subprocess.CalledProcessError: Command '['C:\\Users\\Acer\\.virtualenvs\\tate-bois-96ZGWPKM\\Scripts\\python.exe', '-m',
> 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\Acer\\AppData\\Local\\Temp\\tmp9okbbypj',       
> '--quiet', 'distribute']' returned non-zero exit status 1.
> 
>       The above exception was the direct cause of the following exception:
> 
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "C:\Users\Acer\AppData\Local\Temp\pip-install-0d2di4_i\dotenv_2c6d416c54b94d5991ff437931b4f34c\setup.py", line   
> 13, in <module>
>           setup(name='dotenv',
>         File "C:\Users\Acer\.virtualenvs\tate-bois-96ZGWPKM\lib\site-packages\setuptools\__init__.py", line 86, in setup      
>           _install_setup_requires(attrs)
>         File "C:\Users\Acer\.virtualenvs\tate-bois-96ZGWPKM\lib\site-packages\setuptools\__init__.py", line 80, in
> _install_setup_requires
>           dist.fetch_build_eggs(dist.setup_requires)
>         File "C:\Users\Acer\.virtualenvs\tate-bois-96ZGWPKM\lib\site-packages\setuptools\dist.py", line 874, in
> fetch_build_eggs
>           resolved_dists = pkg_resources.working_set.resolve(
>         File "C:\Users\Acer\.virtualenvs\tate-bois-96ZGWPKM\lib\site-packages\pkg_resources\__init__.py", line 815, in resolve
>           dist = self._resolve_dist(
>         File "C:\Users\Acer\.virtualenvs\tate-bois-96ZGWPKM\lib\site-packages\pkg_resources\__init__.py", line 851, in        
> _resolve_dist
>           dist = best = env.best_match(
>         File "C:\Users\Acer\.virtualenvs\tate-bois-96ZGWPKM\lib\site-packages\pkg_resources\__init__.py", line 1123, in       
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.
> [0m
> This is likely caused by a bug in [32mdotenv[0m. Report this to its maintainers.
> Installation Failed
> ```
> 
> # Pipfile
> ```
> [[source]]
> url = "https://pypi.org/simple"
> verify_ssl = true
> name = "pypi"
> 
> [packages]
> flask = "*"
> flask-login = "*"
> requests = "*"
> 
> [dev-packages]
> autopep8 = "*"
> 
> [requires]
> python_version = "3.10"
> ```

Do you solved it?
I'm facing the same issue

**Comment by heyvoon** [comment]
Having the same issue or similar..

> pip install dotenv
Collecting dotenv
  Using cached dotenv-0.0.5.tar.gz (2.4 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install backend dependencies did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      Collecting distribute
        Using cached distribute-0.7.3.zip (145 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        Preparing metadata (pyproject.toml) did not run successfully.
        exit code: 1

        [6 lines of output]
        usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
           or: setup.py --help [cmd1 cmd2 ...]
           or: setup.py --help-commands
           or: setup.py cmd --help

        error: invalid command 'dist_info'
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed

      Encountered error while generating package metadata.

      See above for output.

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by oelki9** [comment]
same here:
Python 3.10
Pip3: 22.0.2

$ pip install dotenv
Defaulting to user installation because normal site-packages is not writeable
Collecting dotenv
  Downloading dotenv-0.0.5.tar.gz (2.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [64 lines of output]
      /usr/lib/python3/dist-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
        error: subprocess-exited-with-error
      
        × python setup.py egg_info did not run successfully.
        │ exit code: 1
        ╰─> [16 lines of output]
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 14, in <module>
              File "/tmp/pip-wheel-ky5gd2zs/distribute_6c18981a658d48eda01badae3a3ceb29/setuptools/__init__.py", line 2, in <module>
                from setuptools.extension import Extension, Library
              File "/tmp/pip-wheel-ky5gd2zs/distribute_6c18981a658d48eda01badae3a3ceb29/setuptools/extension.py", line 5, in <module>
                from setuptools.dist import _get_unpatched
              File "/tmp/pip-wheel-ky5gd2zs/distribute_6c18981a658d48eda01badae3a3ceb29/setuptools/dist.py", line 7, in <module>
                from setuptools.command.install import install
              File "/tmp/pip-wheel-ky5gd2zs/distribute_6c18981a658d48eda01badae3a3ceb29/setuptools/command/__init__.py", line 8, in <module>
                from setuptools.command import install_scripts
              File "/tmp/pip-wheel-ky5gd2zs/distribute_6c18981a658d48eda01badae3a3ceb29/setuptools/command/install_scripts.py", line 3, in <module>
                from pkg_resources import Distribution, PathMetadata, ensure_directory
              File "/tmp/pip-wheel-ky5gd2zs/distribute_6c18981a658d48eda01badae3a3ceb29/pkg_resources.py", line 1518, in <module>
                register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
            AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
      
      × Encountered error while generating package metadata.
      ╰─> See above for output.
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/setuptools/installer.py", line 82, in fetch_build_egg
          subprocess.check_call(cmd)
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpf5dnrse9', '--quiet', 'distribute']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-t9esd6yd/dotenv_71d652d660ee451384caff4942ff633f/setup.py", line 13, in <module>
          setup(name='dotenv',
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 147, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 812, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 771, in resolve
          dist = best[req.key] = env.best_match(
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1056, in best_match
          return self.obtain(req, installer)
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1068, in obtain
          return installer(requirement)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 883, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/usr/lib/python3/dist-packages/setuptools/installer.py", line 84, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpf5dnrse9', '--quiet', 'distribute']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by tsopanid** [comment]
This repo seems to be dead. 
I solved the same issue (using pip) by switching to [python-dotenv](https://github.com/theskumar/python-dotenv);
```
pip install python-dotenv
```

**Comment by Sayyed-Salman** [comment]
@tsopanid I agree, just use something else.
